### ISSUE TITLE
infografika - wiek - piramida

### ISSUE THREAD

**Issue by MarcinKosinski** [flaminka/WhyR-wiz#1]
Może przerobić wykres z wiekiem tak, zeby pokazywal rowniez plec, np. do postaci piramidy wieku - przyklad tutaj - https://www.google.pl/search?q=piramida+wieku+w+podziale+na+plec&source=lnms&tbm=isch&sa=X&ved=0ahUKEwik5Nzs7tjTAhUEkywKHYQ1AIkQ_AUICigB&biw=1280&bih=615#imgrc=-xfnjGqzWMcv7M:

zwróciłbym także na podpis osi na wykresach: zamiast `ilosc` to może lepiej pisać `ilość` albo najlepiej `liczba uczestników`

**Comment by flaminka** [comment]
Zrobione. Piramidy wieku to świetny pomysł. Zostałam przy liczbie uczestników nie procencie, by przy okazji przynajmniej 1 wykres oddawał proporcję płci jednocześnie.

**Comment by MarcinKosinski** [comment]
No i teraz wygląda super : )
