### ISSUE TITLE
infografika - wyksztalcenie - plec

### ISSUE THREAD

**Issue by MarcinKosinski** [flaminka/WhyR-wiz#2]
To tez fajnie wygladaloby w podziale na plec. Podobnie jak w #1

**Comment by flaminka** [comment]
Zrobione. Tutaj zastosowałam już procenty a etykiety osi Y zostawiłam po lewej by zwrócić pewną uwagę na odmienny typ wykresu (tj. te procenty) trochę.

**Comment by MarcinKosinski** [comment]
Godnie wygląda. Świetna robota.
