### ISSUE TITLE
infografika - doswiadczenie - a wiek

### ISSUE THREAD

**Issue by MarcinKosinski** [flaminka/WhyR-wiz#3]
Moze zastapic gestosc doswiadczenia wykresem prezentujacym jak wiek zalezny jest od doswiadczenia. Doswiadczenie mozna pokolorowac na 2 odrebne kolory, bo prezentujemy 2 rozne doswiadczenia, a ostatecznie do wykresu dodac krzywe regresji? Gestosci mozna dorzucic do wykresu np na osiach obok wykresu (jak tu, pakiet GGally - https://www.google.pl/search?q=ggally+density&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjVtIj_79jTAhUBuSwKHft8Bf8Q_AUICigB&biw=1280&bih=615#tbm=isch&q=ggally+density+on+the+graph+margin&imgrc=xYlPBnOP3mUmZM:

albo 

https://www.google.pl/search?q=ggally+density&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjVtIj_79jTAhUBuSwKHft8Bf8Q_AUICigB&biw=1280&bih=615#tbm=isch&q=ggally+density+on+the+graph+margin&imgrc=ZGfs_V53NrzhUM:

**Comment by flaminka** [comment]
Zrobione (?) Zrobiłam wykres zależności doświadczenia od wieku a nie na odwrót. Wydawał mi się bardziej sensowny. Linie regresji są dodane wprost z ggplota (bez zabawy w poprawę modelu liniowego). Nie wydaje mi się ten wykres najciekawszy, ale na razie zostawiłam wg życzenia.  Zrobienie na marginesach wykresów gęstości - fajny pomysł, ale wiek został pokazany już oddzielnie, nie ma potrzeby powielania informacji wg mnie.

**Comment by MarcinKosinski** [comment]
Na tym wykresie widać (dzięki krzywej regresji), że wraz z wiekiem rośnie również doświadzenie w analizie danych (co jest zrozumiałe) ale nie przekłada się to wcale na doświadczenie w R - duży wiek nie oznacza dużego doświadzenia w R, co jest ciekawym wnioskiem.

Bardzo dziękuję za poprawki.

**Comment by flaminka** [comment]
Nie no ja to widzę, że ta krzywa nie rośnie tak intensywnie i jest to ciekawe :P, ale nie jestem przekonana do umieszczania scatterplotów na wizualizacji - może to się zmieni po tym projekcie ;)
