### ISSUE TITLE
ggploty - motywy graficzne

### ISSUE THREAD

**Issue by MarcinKosinski** [flaminka/WhyR-wiz#4]
Moze wykorzystac jakies schludne szaty graficzne stad - https://github.com/cttobin/ggthemr ?

**Comment by flaminka** [comment]
Wykorzystałam szatę "fresh", jedną z 2 korzystających z białego tła (takie miało pozostać dla zachowania jednolitości wszystkich zakładek). Kolorostykę infografiki podporządkowałam kolorom z tej szaty. Pozmieniałam jednak czcionki by była jednolity Arial wszędzie na infografice.

**Comment by MarcinKosinski** [comment]
Extra, dziękuję.
