### ISSUE TITLE
calosc - napis WhyR?

### ISSUE THREAD

**Issue by MarcinKosinski** [flaminka/WhyR-wiz#5]
Na stronie startowej calosci zamienilbym napis `WhyR?` na `Why R? 2017 `
Tak samo w panelu po lewej gdzie mozna chodzic miedzy zakladkami
Tak samo w `źródło`

**Comment by flaminka** [comment]
Zrobione

**Comment by MarcinKosinski** [comment]
Dzieki, nie wiem czy robilas wszystkie poprawki jednoczesnie czy nie, ale np. dobrym zwyczajem jest robienie jednego commita per rozwiaznie issue - wtedy mozna wskazac w ktorym commitcie coś zostało zmienione. Z drugiej strony pewnie polowa rzeczy tutaj byla robiona w Photoshopie czy czyms podobnym. Teraz po prostu przejrze chyba po prostu cala wizualizacje : ) Jeszcze raz: swietna robota.

**Comment by MarcinKosinski** [comment]
Ok znalazlem jeszcez, ze w infografice pod mapka jest napisane `WhyR?` a mogłoby być `Why R? 2017`

**Comment by flaminka** [comment]
Tak, robiłam poprawki jednocześnie, rozumiem i dzięki za radę, nie mam tego w zwyczaju, a dobrze to wiedzieć :).  Wskażę następnym razem linkiem co zrobiłam, żebyś od razu wiedział gdzie patrzeć.

Np. tutaj, zamiana napisy WhyR na infografice: https://github.com/flaminka/WhyR-wiz/blob/master/infografika.svg

I zmiana nazwy zakładki na Why R? 2017: https://rawgit.com/flaminka/WhyR-wiz/master/calosc.html

**Comment by MarcinKosinski** [comment]
Dzięki, jest bomba! Umieszczamy to jutro na profily Why R? na facebooku, czy umieszczamy na Waszym fanpage'u KNDS i robie udostępnienie na Why R? : )?
