### ISSUE TITLE
calosc - pakiety

### ISSUE THREAD

**Issue by MarcinKosinski** [flaminka/WhyR-wiz#6]
Moze po najechaniu na pakiet dodac informacje do chmurki ze doswiadczenie liczone jest w latach?

**Comment by flaminka** [comment]
Zrobione. Dodawane są końcówki typu: rok roku, lata, lat.

**Comment by MarcinKosinski** [comment]
Extra : )

**Comment by MarcinKosinski** [comment]
Wygląda nieźle. 7 kółek jest niepodpisanych i dopiero widać nazwę po najechaniu na pakiet.
Myślisz, że mają za długie etykiety?

Co powiesz na taki sam wykres, umiejscowiony poniżej obecnego, gdzie na osi pokazana będzie mediana zamiast średniej (Rcmdr jest obarczony obserwacją odstającą i średnia jest wyliczona jedynie z 2ch obserwacji :)?

**Comment by flaminka** [comment]
Poprawki chwilowe są widoczne w wersji dodatkowej wrzuconej (patrz zakładka pakiety):
https://rawgit.com/flaminka/WhyR-wiz/master/calosc%20-%20med.html

Pokazywanie nazw pakietów jest zależne od ich wielkości w zależności od wielkości kółka pakietu, jak przekracza długość napisu wielkość kółka + 8px (tak machnęłam żeby nie było zbyt restrykcyjne) to nie są one pokazywane, Wstawiłam z widocznymi wszystkimi nazwami, jest bajzel. Jak zwiększę limit trochę, to zostanie ich 6 niezapisanych i to ew.  uważam za maksymalny kompromis, bez wrażenia bajzlu. Mozna zmniejszyć czcionkę, ale to doda estetyce, ale nie szybkiemu odczytywaniu napisów.

Co do tego wykresy względem mediany. Mogę zmienić zmienną osi x, ale powtarzanie wykresu pod spodem jest niepotrzebne moim zdaniem. Wstawiam wersję z medianą, bo miałam już ją na wszelki wypadek wyliczoną w danych (tj. w wykresie na razie tylko zmieniłam zmienną generującą skalę x, nie zmieniałam żadnych etykiet czy tooltipow - ak by szybko pokazać, ze za dużych zmian nie ma. Niestety większość tych pakietów ma liczność 2, więc będą takie skrajności, a mediana tego nie zmieni, bo wyjdzie na to samo co średnia dla liczności 2.

**Comment by MarcinKosinski** [comment]
Ok to podpisy pakietów zostawmy.

Co byś powiedziała na to, żeby prezentować tylko pakiety, które zostały
wskazane 3 lub więcej razy?
2 osoby używają jakiegoś pakietu na 169 zapisanych (z czego 161 idzie na
wykłady), to niekoniecznie dobre podsumowanie ogółu : )


W dniu 8 maja 2017 18:58 użytkownik flaminka <notifications@github.com>
napisał:

**Comment by MarcinKosinski** [comment]
Ok to podpisy pakietów zostawmy. - Zostawmy tak jak były przedtem (że 6
pakietów nie widać).

W dniu 8 maja 2017 23:29 użytkownik Marcin Kosiński <m.p.kosinski@gmail.com>
napisał:

**Comment by flaminka** [comment]
Podpisy zostawiłam. I na razie zmieniłam na pakiety wskazane wiecej niz 2 razy (tu, zakladka pakiety https://rawgit.com/flaminka/WhyR-wiz/master/calosc.html ) wygląda to biedniej.

Też się nad tym zastanawiałam z tym 3 i więcej, bo rzeczywiście co nam mówią 2 osoby spośród 169, ale główną ideą tego wykresu było pokazanie jak różne pakiety są używane, tak by móc popatrzeć na te nazwy i stwierdzić: o! ktoś używa takiego pakietu, a ja nawet o nim nie słyszałam; o! tego też nie znam, ciekawe do czego on jest. I o ile zaburzone to jest jeśli chodzi o ośkę, to pokazuje różnorodność. Myślałam o tym bardziej jako o wordcloudzie, który przy okazji jest lekko poukładany poziomo.

W tej chwili z tymi 3 i więcej jest mam wrażenie przewidywalnie, a 3 jest równie małą liczbą co 2. 
Ale mogę jeszcze podyskutować na ten temat.

**Comment by MarcinKosinski** [comment]
To zostańmy przy 2ch i więcej : ) 
Wykres pewnie się jeszcze zmieni może kiedyś, jak dojdą nowe rejestracje.

Marcin Kosinski

Dnia 09.05.2017 o godz. 06:16 flaminka <notifications@github.com> napisał(a):

**Comment by flaminka** [comment]
Zostawiłam jako statystykę średnią (mediana, dla tych 3 skrajnych pakietów jest prawie taka sama, nie poprawia tych skrajności, więc nie zmieniam) i zostawiłam pakiety o liczności 3 i więcej (łącznie chyba 42 pakiety, przy 2 i więcej było koło 75 i to już było przytłaczające).

**Comment by MarcinKosinski** [comment]
Dzięki. Zaktualizowałem właśnie strone whyr.pl/wizualizacje/ : ) wygląda świetnie

**Comment by flaminka** [comment]
;)
