### ISSUE TITLE
Miękki opis

### ISSUE THREAD

**Issue by MarcinKosinski** [flaminka/WhyR-wiz#7]
Dla osób które nie wiedza jak wyglądała rejestracja może warto opisać jak wyglądał proces rejestracji i jakie dane można było zostawić. Taka wizualizacja może zainteresować potencjalnych sponsorów albo potencjalnych mówców z którzy nie spotkali się wcześniej z takim schematem rejestracji : )

**Comment by flaminka** [comment]
Opis zrobiony jako część strony tytułowej. Mam nadzieję, że o coś takiego chodziło.

**Comment by MarcinKosinski** [comment]
Tak dziękuję. Jest super!
